server:
  port: 8081
  servlet.context-path: /sandbox
datasource:
  schema: 'workplace'
  host: '${dockerdbhos:localhost}:3306'
  url: 'jdbc:mariadb://${datasource.host}/${datasource.schema}'
  username: 'root'
  password: 'Alisher2002MySQL'
spring:
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.ddl-auto: none
      hibernate.type: trace
  datasource:
    name: 'workplace'
    driver-class-name: org.mariadb.jdbc.Driver
    url: '${datasource.url}'
    username: '${datasource.username}'
    password: '${datasource.password}'
  liquibase:
    user: '${datasource.username}'
    parameters.env: '${spring.profiles.active}'
    enabled: true
    change-log: '/db.changelog/db.changelog-master.yaml'
