server:
  port: 8081
  servlet.context-path: /sandbox
datasource:
  schema: 'sandbox'
  host: '${dockerdbhost:localhost}:3306'
  url: 'jdbc:mariadb://${datasource.host}/${datasource.schema}'
  username: 'root'
  password: ''
spring:
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.ddl-auto: none
      hibernate.type: trace
  datasource:
    name: 'sandbox'
    driver-class-name: org.mariadb.jdbc.Driver
    url: '${datasource.url}'
    username: '${datasource.username}'
    password: '${datasource.password}'
  liquibase:
    user: '${datasource.username}'
    parameters.env: '${spring.profiles.active}'
    enabled: true
    change-log: '/db.changelog/db.changelog-master.yaml'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    from: 'hotdesktcompany@gmail.com'
    host: 'smtp.gmail.com'
    port: 587
    username: 'hotdesktcompany@gmail.com'
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true